allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
    plugins.withId("com.android.library") {
        project.android {
            compileSdk = 36
            compileSdkVersion = 36
            if (namespace == null) {
                namespace = "dev.isar.${project.name.replace('-', '_')}"
            }
        }
    }
    project.tasks.configureEach { task ->
        if (task.name.contains("verifyReleaseResources")) {
            task.enabled = false
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
